# !: https://code.visualstudio.com/docs/devcontainers/create-dev-container
services:
  backend:
    build:
      target: develop
    ports:
      - 8080:8080
    # NOTE:
    # cached: ホストを信頼し、コンテナ側への反映が遅延することを許容
    # delegated: コンテナ側を信頼し、ホスト側への反映が遅延することを許容
    # volumes:
    #   - ../..:/workspaces:delegated # コンテナに入ってコーディングする場合
    volumes:
      - type: bind
        source: ./backend
        target: /workspace
    command: sleep infinity
    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    # network_mode: service:mysql
