// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateTask(ctx context.Context, arg CreateTaskParams) (sql.Result, error)
	DeleteTask(ctx context.Context, id string) error
	FindTaskByID(ctx context.Context, id string) (*Task, error)
	FindTasksByUserID(ctx context.Context, userID string) ([]*Task, error)
	FindUserByEmail(ctx context.Context, email string) (*User, error)
	FindUserByID(ctx context.Context, id string) (*User, error)
	UpdateTask(ctx context.Context, arg UpdateTaskParams) error
}

var _ Querier = (*Queries)(nil)
